package Forms;

import Connection.Koneksi;
import Default.Menu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DIMAS
 */
public class Form_Penarikan_Uang extends javax.swing.JFrame {

    /**
     * Creates new form Form_Penarikan_Uang
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public Form_Penarikan_Uang() {
        initComponents();
        setTitle("Menu Penarikan");
        tblSaldo.setEnabled(false);
        
        try {
            Connection MySQL = Koneksi.Connect("kas_mhs");
            ResultSet R = MySQL.createStatement().executeQuery("SELECT SUM(nominal) AS SALDO FROM saldo");
            tblSaldo.setModel(DbUtils.resultSetToTableModel(R));
        } catch (SQLException e) {
            System.out.println("Failed To Load :" + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPerihal = new javax.swing.JTextField();
        txtNominal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSaldo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Perihal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        jLabel3.setText("Nominal");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        txtPerihal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerihalActionPerformed(evt);
            }
        });
        jPanel1.add(txtPerihal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 150, -1));
        jPanel1.add(txtNominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 150, -1));

        jButton1.setText("Tarik");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 300, 190);

        jPanel2.setBackground(java.awt.Color.orange);
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("PENARIKAN UANG");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 300, 40);

        tblSaldo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "SALDO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSaldo);
        if (tblSaldo.getColumnModel().getColumnCount() > 0) {
            tblSaldo.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 300, 50);

        setSize(new java.awt.Dimension(332, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String saldo = tblSaldo.getModel().getValueAt(0, 0).toString();
        System.out.println(saldo);
        
        if (txtPerihal.getText().equals("") || txtNominal.getText().equals("") || Integer.parseInt(saldo) < Integer.parseInt(txtNominal.getText())) {
            JOptionPane.showMessageDialog(null, "Data kurang atau Saldo tidak mencukupi");
        } else {
            try {
            String myDriver = "com.mysql.cj.jdbc.Driver";
            String myUrl = "jdbc:mysql://localhost:3306/" + "kas_mhs";
            Class.forName(myDriver);
            
            try (Connection conn = DriverManager.getConnection(myUrl, "root", "")) {
                String query = "INSERT INTO `penarikan`(`id_tarik`, `peruntukan`, `nominal`, `tgl_penarikan`) VALUES (?,?,?,NOW())";
                
                PreparedStatement prpStat = conn.prepareStatement(query);
                prpStat.setInt(1, 0);
                prpStat.setString(2, txtPerihal.getText());
                prpStat.setInt(3, Integer.parseInt(txtNominal.getText()));
                
                prpStat.execute();
                JOptionPane.showMessageDialog(null, "Penarikan Berhasil");
            } catch (Exception e) {
                System.err.print("Got an exception!");
                System.err.println(e.getMessage());
            }
        } catch (ClassNotFoundException e) {
            System.err.print("Got an exception!");
            System.err.println(e.getMessage());
        }
        
        txtPerihal.setText("");
        txtNominal.setText("");
        
        try {
            Connection MySQL = Koneksi.Connect("kas_mhs");
            ResultSet R = MySQL.createStatement().executeQuery("SELECT SUM(nominal) AS SALDO FROM saldo");
            tblSaldo.setModel(DbUtils.resultSetToTableModel(R));
        } catch (SQLException e) {
            System.out.println("Failed To Load :" + e.toString());

        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPerihalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerihalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerihalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Penarikan_Uang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Form_Penarikan_Uang().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSaldo;
    private javax.swing.JTextField txtNominal;
    private javax.swing.JTextField txtPerihal;
    // End of variables declaration//GEN-END:variables
}
